# -*- coding: utf-8 -*-
"""Beginner: Intro to Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ARK_T0bq7jHFuBhnQx3EurKvrW1r46i
"""

print("Hello New Batch")

print ('Hello, My name is Akash Nautiyal')

print('Hello My name is Akash Nautiyal')

print(9)

print (9, "Akash")

print("9") #number as text

print ("Hello"+ "World" ) # added to strings: Concatenation

print ("Hello"+" "+"World")

print('3'+'5")

print("5+10")

print("5'+'10")

print("5"+'10)